WIP | Initial project setup
etherspot/ui pull request #1
Opened 2023-11-29 05:15 UTC by bhumitaylor14

## Description
WIP commit  - project setup through npm library standards

## Motivation and Context
Develop Etherspot UI library for sending native token.

## How Has This Been Tested?
On local machine

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ tick] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-12-04 16:36 UTC, IAmKio requested changes

2023-12-04 16:36 UTC, IAmKio commented on .gitignore
> +node_modules/
Can you please find a  better .gitignore templates for projects like this please?

2023-12-04 16:36 UTC, IAmKio commented on CONTRIBUTING.md
> +## Contributing
Please copy the content from other Etherspot projects here

2023-12-04 16:36 UTC, IAmKio commented on CHANGELOG.md
> +
You've included a package.json update in this PR, please add the change log here

2023-12-04 16:36 UTC, IAmKio commented on SECURITY.md
> +
Please ask DevOps what should go here.

2023-12-04 16:36 UTC, IAmKio commented on __tests__/index.test.js
> +});
Remember newline at the end of the file, do you have editorconfig set up?

2023-12-04 16:36 UTC, IAmKio commented on jest.config.js
> +  };
Remember new line here: https://gist.github.com/OleksiyRudenko/d51388345ea55767b7672307fe35adf3

2023-12-04 16:36 UTC, IAmKio commented on package.json
> +  "version": "1.0.0",
Should this really be `1.0.0`?

2023-12-04 16:36 UTC, IAmKio commented on package.json
> +    "lodash": "^4.17.21"
Please lock these dependencies to prevent code from creeping in

2023-12-04 16:36 UTC, IAmKio commented on src/index.js
> +export default TestModule;
New line

2023-12-05 05:46 UTC, bhumitaylor14 commented
@IAmKio , I have added code for your suggested changes on latest PR

2023-12-05 08:44 UTC, closed without merging