Nftlist component with mock json
etherspot/ui pull request #16
Opened 2024-03-04 06:13 UTC by bhumitaylor14

https://linear.app/pillarproject/issue/PRO-2128/etherspot-ui-nft-list

## Description

Create NFT list component

## How Has This Been Tested?

- tested on local

## Screenshots (if appropriate):
<img width="1790" alt="Screenshot 2024-03-04 at 11 42 09 AM" src="https://github.com/etherspot/ui/assets/141008551/e740dce1-6674-4156-b7f2-59b508dec193">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2024-03-04 06:15 UTC, bhumitaylor14 commented
@kio @lalitkumarrock As per discussion over standup call, I am creating list using mockdata of nftlist. Once project key issue will solve I will uncomment function  and remove mock logic.

2024-03-04 14:19 UTC, lalitkumarrock approved these changes
LGTM!

2024-03-27 05:31 UTC, lalitkumarrock requested changes

2024-03-27 05:31 UTC, lalitkumarrock commented on src/data/mock_nft.json
Remove this file if not required.

2024-03-27 05:31 UTC, lalitkumarrock commented on src/models/NftList.ts
> +  dataApiKey?: string;
`dataApiKey` Move it to Common.ts if used in multiple components

2024-03-27 05:49 UTC, lalitkumarrock approved these changes

2024-03-27 06:08 UTC, merged