Feature/send token UI
etherspot/ui pull request #3
Opened 2023-12-05 05:48 UTC by bhumitaylor14

## Description
WIP commit  - UI integration initial setup rollup config , editor config, suggested changes 

## Motivation and Context
Develop Etherspot UI library for sending native token.

## How Has This Been Tested?
On local machine

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ tick] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-12-05 09:09 UTC, IAmKio requested changes

2023-12-05 09:09 UTC, IAmKio commented on CHANGELOG.md
> +- added contributing , changelog, jest config, security, rollup config, ts config
```suggestion
- added contributing, changelog, jest config, security, rollup config, ts config
```

2023-12-05 09:09 UTC, IAmKio commented on .gitignore
> +dist/
Please find a better .gitignore for node.js / javascript projects

2023-12-05 09:09 UTC, IAmKio commented on package.json
> +    "styled-components": "^5.3.5"
Please version lock these dependencies. Remember when you're building a library, we need to provide stability as a guarantee to the other developers

2023-12-05 09:09 UTC, IAmKio commented on tsconfig.json
Please remove the dead code / config here

2023-12-05 11:16 UTC, bhumitaylor14 commented
@kio suggested changes done

2023-12-07 09:08 UTC, IAmKio approved these changes

2023-12-07 09:09 UTC, merged