PRO-2077 Token List Selector
etherspot/ui pull request #7
Opened 2024-01-03 06:17 UTC by lalitkumarrock

https://linear.app/pillarproject/issue/PRO-2077/story-task-token-list-selector

## Description

- Created TokenSelector component.
- Updated Example UI

## How Has This Been Tested?

- In Storybook
- Local 

## Screenshots (if appropriate):

![Screenshot 2024-01-02 at 1 22 10 PM](https://github.com/etherspot/ui/assets/82652040/0dcd703d-9248-499b-985e-406ce577ca0a)

https://github.com/etherspot/ui/assets/82652040/47e08a13-b6a4-482e-bded-6454dd4fcee4

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2024-01-04 09:25 UTC, IAmKio requested changes
Fantastic work so far 👍 please take a look at the comments that i have left, but progress is very good so far.

2024-01-04 09:25 UTC, IAmKio commented on src/components/TokenSelector/DropDown.tsx
> +    dropDownWidth = '300px',
Just a note that this shouldn't be defined by default. The height and width should default to whatever the DOM default is _until_ the `dropDownHeight` and `dropDownWidth` are defined by the developer.

2024-01-04 09:25 UTC, IAmKio commented on src/components/TokenSelector/index.tsx
> +  const providerWallet = new ethers.Wallet('0x673c79ab4c60f8d9e343aebc147d9e5cd670cab76c7328b03a23d0fef0aa734f');
This needs to be removed and replaced with a provider that is passed as a prop from the developer

2024-01-04 09:25 UTC, IAmKio commented on src/components/TokenSelector/index.tsx
> +    <EtherspotTransactionKit provider={providerWallet} chainId={1}>
Chain ID is locked to 1 here, it needs to be passed in as a prop by the developer

2024-01-04 09:25 UTC, IAmKio commented on src/components/TokenSelector/DropDown.tsx
Just a few things about this file:

- Since this ticket was written, we've changed the standard slightly for how developers style these components. We have now fallen more in line with the `className` property (see the Etherspot UI Transaction History ticket). Please change anything that is called `style` to `elementClassName`, for example `dropdownContainerClassName`
- Any element that can accept a `className` should accept a developer defined `className` as a top-level component prop 
- Please note that `dropDown` is not two different words, it's one word these days. The correct way to use it is just `dropdown` (no capitalisation on the second D). Please change these references in this file and filenames.
- Please annotate the entire file to describe what is happening where possible.

2024-01-04 10:06 UTC, lalitkumarrock commented on src/components/TokenSelector/index.tsx
> +  const providerWallet = new ethers.Wallet('0x673c79ab4c60f8d9e343aebc147d9e5cd670cab76c7328b03a23d0fef0aa734f');
I think provider, chainId, debug, etc props passing in each component is bad thing.
Can we make a separate method for this?

2024-01-04 14:01 UTC, lalitkumarrock commented on src/components/TokenSelector/DropDown.tsx
> +    dropDownWidth = '300px',
Removed default height and width.

2024-01-04 14:02 UTC, lalitkumarrock commented on src/components/TokenSelector/index.tsx
> +  const providerWallet = new ethers.Wallet('0x673c79ab4c60f8d9e343aebc147d9e5cd670cab76c7328b03a23d0fef0aa734f');
Now provider passed as prop

2024-01-04 14:02 UTC, lalitkumarrock commented on src/components/TokenSelector/index.tsx
> +    <EtherspotTransactionKit provider={providerWallet} chainId={1}>
Now chainId passed as props

2024-01-04 14:02 UTC, lalitkumarrock commented on src/components/TokenSelector/DropDown.tsx
Updated it!

2024-01-08 08:43 UTC, IAmKio requested changes
Just one tiny change and i would consider this complete

2024-01-08 08:43 UTC, IAmKio commented on src/components/TokenSelector/DropDown.tsx
> +                            alt="new"
```suggestion
                            alt={`${name} (${symbol}) image`}
```

2024-01-08 08:47 UTC, IAmKio approved these changes
Great work - LGTM

2024-01-08 08:54 UTC, closed without merging

2024-01-08 08:55 UTC, lalitkumarrock commented
Pull origin develop

2024-01-08 08:55 UTC, lalitkumarrock commented
Pull origin